/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DeliveryManagerRole;

import EcoSystem.Employee.Employee;
import EcoSystem.Enterprise.Billing_ShipmentEnterprise;
import EcoSystem.Enterprise.Enterprise;
import EcoSystem.Network.Network;
import EcoSystem.Organization.DeliveryOrganization;
import EcoSystem.Organization.Organization;
import EcoSystem.Role.DeliveryManRole;
import EcoSystem.UserAccount.UserAccount;
import EcoSystem.WorkQueue.DeliveryProductWorkRequest;
import EcoSystem.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucy Bai
 */
public class EnsureDelivery extends javax.swing.JPanel {

    /**
     * Creates new form EnsureDelivery
     */
 private JPanel userProcessContainer;
 private Enterprise enterprise;
 private DeliveryOrganization deliveryOrganization;
 private Network network;
   public EnsureDelivery(JPanel userProcessContainer, Enterprise enterprise, DeliveryOrganization deliveryOrganization,Network network) {
      initComponents();
      this.userProcessContainer=userProcessContainer;
      this.enterprise=enterprise;
      this.deliveryOrganization=deliveryOrganization;
      this.network=network;
      populateTable();
      populateCombo();
    }
   public void populateCombo(){
           
  
        comboEmployee.removeAllItems();
        for(UserAccount userAccount: deliveryOrganization.getUserAccountDirectory().getUserAccountList()) {
            if(userAccount.getRole() instanceof DeliveryManRole)
                comboEmployee.addItem(userAccount.getEmployee());
        }
    
   }
  public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblDelivery.getModel();
        dtm.setRowCount(0);
        for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()){
            if(enterprise instanceof Billing_ShipmentEnterprise){
                for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
                    if(org instanceof DeliveryOrganization){
                        if(org==deliveryOrganization){
                            for( WorkRequest wk:org.getWorkQueue().getWorkRequestList()){
                                if(wk instanceof DeliveryProductWorkRequest){
                                    Object row[]=new Object[4];
                                     row[0]=wk;
                                     row[1]= ((DeliveryProductWorkRequest) wk).getOrder();
                                     row[2]=((DeliveryProductWorkRequest) wk).getRequestDate();
                                     row[3]=wk.getStatus();
                                     dtm.addRow(row);
                                } 
                            }
                        }
                    }
                }
            }
        }
        
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDelivery = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        comboEmployee = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("Ensure Delivery");

        tblDelivery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order", "Sender", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDelivery);
        if (tblDelivery.getColumnModel().getColumnCount() > 0) {
            tblDelivery.getColumnModel().getColumn(0).setResizable(false);
            tblDelivery.getColumnModel().getColumn(1).setResizable(false);
            tblDelivery.getColumnModel().getColumn(2).setResizable(false);
            tblDelivery.getColumnModel().getColumn(3).setResizable(false);
        }

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        jLabel1.setText("Employees:");

        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(comboEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnAssign))
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDelivery.getSelectedRow();
        if( selectedRow >= 0 ) {  
        DeliveryProductWorkRequest dw=(DeliveryProductWorkRequest)tblDelivery.getValueAt(selectedRow, 0);
        Employee em=(Employee)comboEmployee.getSelectedItem();
        dw.setStatus("Out of delivery");
        dw.setEmployee(em);
        populateTable();
        

        }
        else{
             JOptionPane.showMessageDialog(null, "Please select a row!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox comboEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDelivery;
    // End of variables declaration//GEN-END:variables
}
