/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.StoreManager;

import EcoSystem.DeliveryPrice.DeliveryPrice;
import EcoSystem.Enterprise.Billing_ShipmentEnterprise;
import EcoSystem.Enterprise.Enterprise;
import EcoSystem.Network.Network;
import EcoSystem.Order.Order;
import EcoSystem.Organization.DeliveryOrganization;
import EcoSystem.Organization.Organization;
import EcoSystem.UserAccount.UserAccount;
import EcoSystem.WorkQueue.DeliveryProductWorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author Lucy Bai
 */
public class ChooseDelivery extends javax.swing.JPanel {

    /**
     * Creates new form ChooseDelivery
     */
 private JPanel userProcessContainer;
 private Enterprise enterprise;
 private Order or;
 private Network network;
 private UserAccount userAccount;
    public ChooseDelivery(JPanel userProcessContainer, Enterprise enterprise, Order or,Network network,UserAccount userAccount) {
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.or=or;
        this.network=network;
        this.userAccount=userAccount;
        this.userAccount=userAccount;
        initComponents();
        lblOrder.setText(String.valueOf(or.getOrderId()));
        propulateEnterpriseCombo();
    }

  public void   propulateEnterpriseCombo(){
      for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
        for(Organization organization :enterprise.getOrganizationDirectory().getOrganizationList() ){
            if(organization instanceof DeliveryOrganization){
                comboDelivery.addItem((DeliveryOrganization)organization);
            }
        }
      }
  }
  public void propulateServiceCombo(DeliveryOrganization org){
         comboService.removeAllItems();
         for(DeliveryPrice dp:org.getPrice().getDeliveryPriceCatalog()){
             comboService.addItem(dp);
         }
  }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        comboDelivery = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        lblOrder = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEnsure = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboService = new javax.swing.JComboBox();
        btnCaculate = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("Delivery Option");

        comboDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDeliveryActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblOrder.setText("Order ");

        jLabel2.setText("Start to place");

        btnEnsure.setText("Ensure");
        btnEnsure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnsureActionPerformed(evt);
            }
        });

        jLabel1.setText("Weight:");

        jLabel3.setText("Choose Delivery enterprise:");

        jLabel4.setText("Choose Service:");

        btnCaculate.setText("Caculate");
        btnCaculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnsure, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCaculate)
                                .addGap(32, 32, 32)
                                .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                            .addComponent(comboDelivery, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4))
                            .addComponent(comboService, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtWeight))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOrder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel6)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrder)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(comboDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(comboService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaculate)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnEnsure, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDeliveryActionPerformed
        // TODO add your handling code here:
        DeliveryOrganization organization = (DeliveryOrganization) comboDelivery.getSelectedItem();
        if (organization != null){
          propulateServiceCombo(organization);}
        
    }//GEN-LAST:event_comboDeliveryActionPerformed

    private void btnEnsureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnsureActionPerformed
        // TODO add your handling code here:
        Organization org =(Organization)comboDelivery.getSelectedItem();
           
       
            DeliveryProductWorkRequest dpw = new DeliveryProductWorkRequest();
            dpw.setOrder(or);
            dpw.setSender(userAccount);
             Date date =new Date();
            dpw.setRequestDate(date);
            dpw.setStatus("Processing");
            
           for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()){
               if(enterprise instanceof Billing_ShipmentEnterprise){
                   for(Organization or: enterprise.getOrganizationDirectory().getOrganizationList()){
                       if(or==org){
                           or.getWorkQueue().getWorkRequestList().add(dpw);
                       }
                   }
               }
           }
        
        
        
        
        
    }//GEN-LAST:event_btnEnsureActionPerformed

    private void btnCaculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaculateActionPerformed
        // TODO add your handling code here:
        Double weight=Double.valueOf(txtWeight.getText());
        DeliveryPrice dp=(DeliveryPrice)comboService.getSelectedItem();
        if(weight <= 3){
            txtPrice.setText(String.valueOf(dp.getStanderedPrice()));
        }
        else{
            txtPrice.setText(String.valueOf(dp.getStanderedPrice()+(weight-3)*(dp.getPerPrice())));
        }
    }//GEN-LAST:event_btnCaculateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCaculate;
    private javax.swing.JButton btnEnsure;
    private javax.swing.JComboBox comboDelivery;
    private javax.swing.JComboBox comboService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
