/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Billing_ShipmentEnterprise;
import EcoSystem.Enterprise.Enterprise;
import EcoSystem.Network.Network;
import EcoSystem.Order.Order;
import EcoSystem.Order.OrderItem;
import EcoSystem.Organization.BillingOrganization;
import EcoSystem.Organization.Organization;
import EcoSystem.Organization.StoreOrganization;
import EcoSystem.UserAccount.UserAccount;
import EcoSystem.WorkQueue.OrderPlaceWorkRequest;
import EcoSystem.WorkQueue.ProductBillingWorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucy Bai
 */
public final class CheckOutProduct extends javax.swing.JPanel {
    
    /**
     * Creates new form CheckOutProduct
     */
 
    private JPanel userProcessContainer;
    private UserAccount account;
    private Order or;
    private Enterprise enterprise;
    private EcoSystem system;
    private Network network;
    
    public  CheckOutProduct(JPanel userProcessContainer, UserAccount account, Order or, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.or=or;
        this.system=system;
        this.enterprise=enterprise;
        this.network = whatNetwork();
        populateTable();
    }
     
    public final Network whatNetwork() {
        Network n = null;
        for(Network network: system.getNetworkList()) {
            for( Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList() ) {
                if( enterprise == this.enterprise ) {
                    n = network;
                    break;
                }
            }
        }
        return n;
    }
     
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblOrder.getModel();
        dtm.setRowCount(0);
        for(OrderItem oi: or.getOrderItemList()) {
            Object row[] = new Object[5];
            row[0] = oi;
            row[1] = oi.getStoreOrganization().getStoreType();
            row[2] = oi.getSalesPrice();
            row[3] = oi.getQuantity();
            row[4] = oi.getStoreOrganization();  
            dtm.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnCheckOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        radioDelivery = new javax.swing.JRadioButton();
        radioPick = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Check Out");

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductName", "Type", "Price", "Quantity", "Store"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOrder);

        btnCheckOut.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCheckOut.setText("Check Out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        jLabel2.setText("Choose your way to get products: ");

        buttonGroup1.add(radioDelivery);
        radioDelivery.setText("Delivery");

        buttonGroup1.add(radioPick);
        radioPick.setText("Pick Up");

        jLabel3.setText("Address:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioPick)
                                            .addComponent(radioDelivery)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(287, 287, 287)
                                        .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioDelivery)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioPick))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(btnCheckOut))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
        int dialogButton=JOptionPane.YES_NO_OPTION;
        int dialogResult=JOptionPane.showConfirmDialog(null,"Would you like to check out?","Warning",dialogButton);
        if(dialogResult==JOptionPane.YES_OPTION){
              
            if(radioDelivery.isSelected()){
                or.setDelivery(true);
            } 
            else if(radioPick.isSelected()){
                or.setDelivery(false);
            }
            
            Date date =new Date();
            or.setDate(date);
            or.setAddress(txtAddress.getText());
            // or.setPaid(true);
            ProductBillingWorkRequest pb = new ProductBillingWorkRequest();
            pb.setOrder(or);
            pb.setSender(account);
            pb.setRequestDate(date);
            pb.setStatus("Processing");
            
            Organization org = null;
            for(Enterprise e: network.getEnterpriseDirectory().getEnterpriseList()) {
                if(e instanceof Billing_ShipmentEnterprise) {
                    for(Organization o: e.getOrganizationDirectory().getOrganizationList()) {
                        if( o instanceof BillingOrganization) {
                            org = o;
                            break;
                        }
                    }
                }
            }
            if( org != null ) {
                account.getWorkQueue().getWorkRequestList().add(pb);
                org.getWorkQueue().getWorkRequestList().add(pb);
                for(Organization o: enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if(o instanceof StoreOrganization) {
                        for(OrderItem oi: or.getOrderItemList()) {
                            if(oi.getStoreOrganization() == o) {
                                OrderPlaceWorkRequest opwr = new OrderPlaceWorkRequest();
                                Order order = new Order();
                                Order.count--;
                                order.getOrderItemList().add(oi);
                                opwr.setOrder(or);
                                opwr.setOrderId(or.getOrderId());
                                opwr.setSender(account);
                                opwr.setRequestDate(date);
                                opwr.setStatus("Pending");
                                o.getWorkQueue().getWorkRequestList().add(opwr);
                            }
                        }
                    }
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "Sorry for the inconvenience \n We are setting up the Billing", "Our Fault! Bad Programmars!", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            
        }
    }//GEN-LAST:event_btnCheckOutActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radioDelivery;
    private javax.swing.JRadioButton radioPick;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtAddress;
    // End of variables declaration//GEN-END:variables
}
